name: Sandbox Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to SANDBOX
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.SANDBOX_IP }}
          port: 33899
          username: ${{ secrets.SANDBOX_USER }}
          password: ${{ secrets.SANDBOX_PASSWORD }}

          script: |
            echo "STARTING SANDBOX DEPLOY"

            echo "STEP 1: Enter project directory"
            cd C:\inetpub\wwwroot\Sandbox_CareIT_Vibe_Miniapp

            echo "STEP 2: Fetchs latest code"
            git fetch origin

            echo "STEP 3: Reset to origin/main"
            git reset --hard origin/main

            echo "STEP 4: Restart IIS"
            iisreset

              echo "SANDBOX DEPLOY COMPLETE"q2